/**
 * Scaffold for LangChain.js projects.
 *
 * Generates a `weave-security.ts` module that wires up:
 *   - WeaveSecurityCallback for input/output scanning
 *   - Optional Tollere pre-flight check for dependency safety
 *   - Optional Hundredmen MCP interception (if user uses MCP)
 */

import type { ScaffoldOutput, ScaffoldOptions } from "./types.js";

export function scaffoldLangChainJS(opts: ScaffoldOptions): ScaffoldOutput {
  const ext = opts.language === "typescript" ? "ts" : "js";
  const has = (p: string) => opts.selectedPackages.includes(p as never);

  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * Weave Protocol security middleware for LangChain.js");
  lines.push(" * Generated by `weave init`");
  lines.push(" */");
  lines.push("");

  if (has("langchain")) {
    lines.push(`import { WeaveSecurityCallback } from "@weave_protocol/langchain";`);
  }
  if (has("hundredmen")) {
    lines.push(`import { Interceptor } from "@weave_protocol/hundredmen";`);
  }
  if (has("tollere")) {
    lines.push(`import { scanPackageJson } from "@weave_protocol/tollere";`);
    lines.push(`import { readFileSync } from "node:fs";`);
  }
  lines.push("");

  // ──────────────────────────────────────────────────────
  // Security callback for any LangChain chain/agent
  // ──────────────────────────────────────────────────────
  if (has("langchain")) {
    lines.push("/**");
    lines.push(" * Drop this into any LangChain LLMChain/agent's `callbacks` array.");
    lines.push(" * It scans inputs and outputs for secrets, PII, and prompt injection.");
    lines.push(" */");
    lines.push("export const securityCallback = new WeaveSecurityCallback({");
    lines.push(`  action: "block",          // "block" | "warn" | "log"`);
    lines.push(`  minSeverity: "medium",`);
    lines.push("  scanTools: true,");
    lines.push("  scanRetrievers: true,");
    lines.push("});");
    lines.push("");
  }

  // ──────────────────────────────────────────────────────
  // Hundredmen MCP interceptor
  // ──────────────────────────────────────────────────────
  if (has("hundredmen")) {
    lines.push("/**");
    lines.push(" * If your agent calls MCP tools, route them through this interceptor");
    lines.push(' * to detect "said X, doing Y" drift and gate high-risk operations.');
    lines.push(" */");
    lines.push("export const mcpInterceptor = new Interceptor({");
    lines.push(`  mode: "active",           // "passive" | "active" | "strict"`);
    lines.push("  driftDetectionEnabled: true,");
    lines.push("  reputationEnabled: true,");
    lines.push("  minReputationScore: 30,");
    lines.push("});");
    lines.push("");
  }

  // ──────────────────────────────────────────────────────
  // Tollere pre-flight
  // ──────────────────────────────────────────────────────
  if (has("tollere")) {
    lines.push("/**");
    lines.push(" * Optional: run this in CI or at boot to catch supply chain risks");
    lines.push(" * before they reach production.");
    lines.push(" */");
    lines.push("export async function auditDependencies() {");
    lines.push(`  const pkgJson = readFileSync("./package.json", "utf8");`);
    lines.push(`  const report = await scanPackageJson(pkgJson);`);
    lines.push(`  if (report.recommendation === "BLOCK_INSTALL") {`);
    lines.push(`    console.error("🛂 Tollere blocked install:", report.blockedPackages);`);
    lines.push(`    process.exit(1);`);
    lines.push("  }");
    lines.push("  return report;");
    lines.push("}");
    lines.push("");
  }

  // ──────────────────────────────────────────────────────
  // Usage hint
  // ──────────────────────────────────────────────────────
  lines.push("/*");
  lines.push(" * Usage in your chain or agent:");
  lines.push(" *");
  lines.push(' *   import { ChatOpenAI } from "@langchain/openai";');
  lines.push(' *   import { LLMChain } from "langchain/chains";');
  lines.push(' *   import { securityCallback } from "./weave-security";');
  lines.push(" *");
  lines.push(" *   const chain = new LLMChain({");
  lines.push(" *     llm: new ChatOpenAI(),");
  lines.push(" *     prompt,");
  lines.push(" *     callbacks: [securityCallback],");
  lines.push(" *   });");
  lines.push(" */");
  lines.push("");

  return {
    packages: [
      "@weave_protocol/langchain",
      ...(has("hundredmen") ? ["@weave_protocol/hundredmen"] : []),
      ...(has("tollere") ? ["@weave_protocol/tollere"] : []),
      ...(has("mund") ? ["@weave_protocol/mund"] : []),
    ],
    files: [
      {
        path: `weave-security.${ext}`,
        content: lines.join("\n"),
        description: "Security middleware module",
      },
    ],
    configEntries: [
      { key: "framework", value: "langchain-js" },
      { key: "language", value: opts.language },
    ],
    nextSteps: [
      `Import the security callback in your chains: import { securityCallback } from "./weave-security"`,
      `Add it to any chain's \`callbacks\` array`,
      ...(has("tollere")
        ? [`Run \`npx weave audit\` (or \`npm run weave:audit\`) before each deploy to scan dependencies`]
        : []),
      ...(has("hundredmen")
        ? [`If using MCP tools, route them through \`mcpInterceptor\` to catch drift`]
        : []),
    ],
  };
}
