/**
 * Scaffold for projects building MCP servers.
 *
 * The most important security move for an MCP server is wrapping every
 * tool handler in a Mund scan and (optionally) routing through Hundredmen.
 */

import type { ScaffoldOutput, ScaffoldOptions } from "./types.js";

export function scaffoldMcpServer(opts: ScaffoldOptions): ScaffoldOutput {
  const ext = opts.language === "typescript" ? "ts" : "js";
  const has = (p: string) => opts.selectedPackages.includes(p as never);
  const isTS = opts.language === "typescript";
  const t = (type: string) => (isTS ? type : "");

  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * Weave Protocol security middleware for MCP servers");
  lines.push(" * Generated by `weave init`");
  lines.push(" *");
  lines.push(" * Wrap your tool handlers with `secureToolHandler` to automatically");
  lines.push(" * scan inputs and outputs for secrets, PII, and injection.");
  lines.push(" */");
  lines.push("");

  if (has("mund")) {
    lines.push(`import { scan } from "@weave_protocol/mund";`);
  }
  if (has("domere")) {
    lines.push(`import { ComplianceManager } from "@weave_protocol/domere";`);
  }
  lines.push("");

  if (has("mund")) {
    lines.push(`type ToolHandler = (args${t(": any")}) => ${t("Promise<any> | any")} ${isTS ? "" : ""};`);
    lines.push("");
    lines.push("/**");
    lines.push(" * Wraps an MCP tool handler with Mund input/output scanning.");
    lines.push(" *");
    lines.push(" *   server.setRequestHandler(CallToolRequestSchema, secureToolHandler(async ({ args }) => {");
    lines.push(" *     return await myToolLogic(args);");
    lines.push(" *   }));");
    lines.push(" */");
    lines.push(`export function secureToolHandler(handler${t(": ToolHandler")})${t(": ToolHandler")} {`);
    lines.push(`  return async (args${t(": any")}) => {`);
    lines.push(`    // Scan inputs`);
    lines.push(`    const inputStr = JSON.stringify(args);`);
    lines.push(`    const inputScan = await scan(inputStr);`);
    lines.push(`    if (!inputScan.safe) {`);
    lines.push(`      const critical = inputScan.issues.filter((i${t(": any")}) => i.severity === "critical");`);
    lines.push(`      if (critical.length > 0) {`);
    lines.push(`        return {`);
    lines.push(`          content: [{ type: "text", text: \`Blocked by Weave Mund: \${critical[0].description}\` }],`);
    lines.push(`          isError: true,`);
    lines.push("        };");
    lines.push("      }");
    lines.push("    }");
    lines.push("");
    lines.push(`    // Run the actual tool`);
    lines.push(`    const result = await handler(args);`);
    lines.push("");
    lines.push(`    // Scan outputs`);
    lines.push(`    const outputStr = JSON.stringify(result);`);
    lines.push(`    const outputScan = await scan(outputStr);`);
    lines.push(`    if (!outputScan.safe) {`);
    lines.push(`      const critical = outputScan.issues.filter((i${t(": any")}) => i.severity === "critical");`);
    lines.push(`      if (critical.length > 0) {`);
    lines.push(`        return {`);
    lines.push(`          content: [{ type: "text", text: "Tool output blocked: contained sensitive data" }],`);
    lines.push(`          isError: true,`);
    lines.push("        };");
    lines.push("      }");
    lines.push("    }");
    lines.push("");
    lines.push(`    return result;`);
    lines.push("  };");
    lines.push("}");
    lines.push("");
  }

  if (has("domere")) {
    lines.push("/**");
    lines.push(" * Optional: log every tool call as a tamper-evident compliance checkpoint.");
    lines.push(' * Configure frameworks based on your environment ("soc2", "hipaa", etc.).');
    lines.push(" */");
    lines.push(`export const compliance = new ComplianceManager(["soc2"]);`);
    lines.push("");
  }

  return {
    packages: [
      ...(has("mund") ? ["@weave_protocol/mund"] : []),
      ...(has("domere") ? ["@weave_protocol/domere"] : []),
      ...(has("tollere") ? ["@weave_protocol/tollere"] : []),
    ],
    files: [
      {
        path: `weave-security.${ext}`,
        content: lines.join("\n"),
        description: "MCP tool handler wrapper",
      },
    ],
    configEntries: [
      { key: "framework", value: "mcp-server" },
      { key: "language", value: opts.language },
    ],
    nextSteps: [
      `Import the wrapper: import { secureToolHandler } from "./weave-security"`,
      `Wrap each tool handler: server.setRequestHandler(schema, secureToolHandler(myHandler))`,
      ...(has("domere") ? [`Add compliance checkpoints in critical tool handlers`] : []),
      ...(has("tollere") ? [`Run \`npx weave audit\` regularly to scan dependencies`] : []),
    ],
  };
}
