/**
 * Scaffold for raw OpenAI / Anthropic SDK projects (no framework wrapper).
 *
 * Generates a small wrapper that scans inputs/outputs through Mund before
 * and after each LLM call. Works for both vendors.
 */

import type { ScaffoldOutput, ScaffoldOptions } from "./types.js";

export function scaffoldSDK(opts: ScaffoldOptions, vendor: "openai" | "anthropic"): ScaffoldOutput {
  const ext = opts.language === "typescript" ? "ts" : "js";
  const has = (p: string) => opts.selectedPackages.includes(p as never);

  const isTS = opts.language === "typescript";
  const t = (type: string) => (isTS ? type : "");

  const lines: string[] = [];
  lines.push("/**");
  lines.push(` * Weave Protocol security wrapper for the ${vendor === "openai" ? "OpenAI" : "Anthropic"} SDK`);
  lines.push(" * Generated by `weave init`");
  lines.push(" */");
  lines.push("");

  if (has("mund")) {
    lines.push(`import { scan } from "@weave_protocol/mund";`);
  }
  if (has("hord")) {
    lines.push(`import { YoxallismusCipher } from "@weave_protocol/hord";`);
  }
  lines.push("");

  // Generic scanInput/scanOutput helpers
  if (has("mund")) {
    lines.push("/**");
    lines.push(" * Scan a string for secrets, PII, and prompt injection.");
    lines.push(" * Throws if the content contains critical issues.");
    lines.push(" */");
    lines.push(`export async function scanContent(content${t(": string")})${t(": Promise<string>")} {`);
    lines.push(`  const result = await scan(content);`);
    lines.push(`  if (!result.safe) {`);
    lines.push(`    const critical = result.issues.filter((i${t(": any")}) => i.severity === "critical");`);
    lines.push(`    if (critical.length > 0) {`);
    lines.push("      throw new Error(");
    lines.push("        `Weave Mund blocked content: ${critical.map((c" + t(": any") + ") => c.type).join(\", \")}`");
    lines.push("      );");
    lines.push("    }");
    lines.push(`    console.warn("⚠️  Weave Mund flagged:", result.issues);`);
    lines.push("  }");
    lines.push(`  return content;`);
    lines.push("}");
    lines.push("");

    if (vendor === "openai") {
      lines.push("/**");
      lines.push(" * Wrap an OpenAI chat completion with input/output scanning.");
      lines.push(" *");
      lines.push(" *   const safe = await secureChatCompletion(openai, {");
      lines.push(' *     model: "gpt-4",');
      lines.push(' *     messages: [{ role: "user", content: userInput }],');
      lines.push(" *   });");
      lines.push(" */");
      lines.push(`export async function secureChatCompletion(openai${t(": any")}, params${t(": any")})${t(": Promise<any>")} {`);
      lines.push(`  for (const m of params.messages || []) {`);
      lines.push(`    if (typeof m.content === "string") await scanContent(m.content);`);
      lines.push("  }");
      lines.push(`  const response = await openai.chat.completions.create(params);`);
      lines.push(`  const reply = response.choices?.[0]?.message?.content;`);
      lines.push(`  if (typeof reply === "string") await scanContent(reply);`);
      lines.push(`  return response;`);
      lines.push("}");
    } else {
      lines.push("/**");
      lines.push(" * Wrap an Anthropic message creation with input/output scanning.");
      lines.push(" */");
      lines.push(`export async function secureMessages(anthropic${t(": any")}, params${t(": any")})${t(": Promise<any>")} {`);
      lines.push(`  for (const m of params.messages || []) {`);
      lines.push(`    if (typeof m.content === "string") await scanContent(m.content);`);
      lines.push("  }");
      lines.push(`  const response = await anthropic.messages.create(params);`);
      lines.push(`  for (const block of response.content || []) {`);
      lines.push(`    if (block.type === "text") await scanContent(block.text);`);
      lines.push("  }");
      lines.push(`  return response;`);
      lines.push("}");
    }
    lines.push("");
  }

  if (has("hord")) {
    lines.push("/**");
    lines.push(" * Encrypted storage for API keys and other secrets.");
    lines.push(" * Replace `process.env.MASTER_KEY` with your KMS-derived key in production.");
    lines.push(" */");
    lines.push(`export const vault = new YoxallismusCipher(process.env.MASTER_KEY${t(" || \"\"")});`);
    lines.push("");
  }

  return {
    packages: [
      ...(has("mund") ? ["@weave_protocol/mund"] : []),
      ...(has("hord") ? ["@weave_protocol/hord"] : []),
      ...(has("tollere") ? ["@weave_protocol/tollere"] : []),
    ],
    files: [
      {
        path: `weave-security.${ext}`,
        content: lines.join("\n"),
        description: `Security wrapper for ${vendor === "openai" ? "OpenAI" : "Anthropic"} SDK`,
      },
    ],
    configEntries: [
      { key: "framework", value: vendor === "openai" ? "openai-sdk" : "anthropic-sdk" },
      { key: "language", value: opts.language },
    ],
    nextSteps: [
      `Import the wrapper: import { secure${vendor === "openai" ? "ChatCompletion" : "Messages"} } from "./weave-security"`,
      `Use it in place of direct SDK calls`,
      ...(has("tollere") ? [`Run \`npx weave audit\` to scan your dependencies`] : []),
    ],
  };
}
