/**
 * Markdown scorecard reporter.
 *
 * Designed to be pasted into a GitHub issue, blog post, or CI comment.
 * Plays well in monospace terminals (uses tables, no fancy unicode).
 */

import type { Scorecard, AttackResult, AttackSeverity } from '../types.js';

const RESULT_BADGE: Record<AttackResult, string> = {
  blocked: '🟢 blocked',
  partial: '🟡 partial',
  breached: '🔴 breached',
};

const SEV_BADGE: Record<AttackSeverity, string> = {
  low: '🔵 LOW',
  medium: '🟡 MED',
  high: '🟠 HIGH',
  critical: '🔴 CRIT',
};

export function renderMarkdownScorecard(scorecard: Scorecard): string {
  const lines: string[] = [];
  const { target, ward, summary, findings, startedAt, durationMs, adversaryVersion } = scorecard;

  lines.push(`# Adversary scorecard`);
  lines.push('');
  lines.push(`**Target:** \`${target.kind}\` · ${target.identifier}`);
  lines.push(`**Run:** ${new Date(startedAt).toISOString()} · ${(durationMs / 1000).toFixed(1)}s`);
  lines.push(`**Adversary:** v${adversaryVersion} · schema v${scorecard.schemaVersion}`);
  if (ward) {
    lines.push(
      ward.loaded
        ? `**WARD policy:** ✓ \`${ward.source || '(unknown)'}\` (${ward.rulesProbed} relevant rules probed)`
        : `**WARD policy:** _none loaded_`,
    );
  }
  lines.push('');

  // ─── Score banner ───────────────────────────────────────────
  const scoreEmoji = summary.score >= 90 ? '🟢' : summary.score >= 70 ? '🟡' : summary.score >= 50 ? '🟠' : '🔴';
  lines.push(`## ${scoreEmoji} Score: **${summary.score}** / 100`);
  lines.push('');
  lines.push(
    `${summary.total} attacks · 🟢 ${summary.blocked} blocked · 🟡 ${summary.partial} partial · 🔴 ${summary.breached} breached`,
  );
  lines.push('');

  // ─── By category ────────────────────────────────────────────
  lines.push(`### By category`);
  lines.push('');
  lines.push('| Category | Total | 🟢 Blocked | 🟡 Partial | 🔴 Breached |');
  lines.push('|---|--:|--:|--:|--:|');
  for (const [cat, data] of Object.entries(summary.byCategory)) {
    if (!data) continue;
    lines.push(`| \`${cat}\` | ${data.total} | ${data.blocked} | ${data.partial} | ${data.breached} |`);
  }
  lines.push('');

  // ─── By severity ────────────────────────────────────────────
  lines.push(`### By severity`);
  lines.push('');
  lines.push('| Severity | Total | 🟢 Blocked | 🟡 Partial | 🔴 Breached |');
  lines.push('|---|--:|--:|--:|--:|');
  for (const sev of ['critical', 'high', 'medium', 'low'] as AttackSeverity[]) {
    const data = summary.bySeverity[sev];
    if (!data) continue;
    lines.push(`| ${SEV_BADGE[sev]} | ${data.total} | ${data.blocked} | ${data.partial} | ${data.breached} |`);
  }
  lines.push('');

  // ─── Breaches (the critical findings) ──────────────────────
  const breaches = findings.filter((f) => f.result === 'breached');
  if (breaches.length) {
    lines.push(`### 🔴 Breaches (${breaches.length})`);
    lines.push('');
    lines.push('These are attacks where the agent took the bait — made hostile tool calls, leaked data, or executed adversarial directives.');
    lines.push('');
    for (const f of breaches) {
      lines.push(`#### \`${f.attackId}\` (${SEV_BADGE[f.severity]})`);
      lines.push('');
      lines.push(`**Evidence:**`);
      lines.push('```');
      lines.push(truncate(f.evidence, 800));
      lines.push('```');
      if (f.toolCallsMade?.length) {
        lines.push(`**Tool calls made:**`);
        for (const tc of f.toolCallsMade) {
          lines.push(`- \`${tc.name}(${JSON.stringify(tc.arguments)})\``);
        }
      }
      if (f.wardRuleViolated) {
        lines.push(`**WARD rule violated:** \`${f.wardRuleViolated}\``);
      }
      lines.push('');
    }
  }

  // ─── Partials ───────────────────────────────────────────────
  const partials = findings.filter((f) => f.result === 'partial');
  if (partials.length) {
    lines.push(`### 🟡 Partial (${partials.length})`);
    lines.push('');
    lines.push('Verbal compliance without action — the agent acknowledged the attack but did not (yet) call hostile tools. Still a leak/jailbreak surface.');
    lines.push('');
    for (const f of partials.slice(0, 10)) {
      lines.push(`- \`${f.attackId}\` ${SEV_BADGE[f.severity]} — ${truncate(f.evidence, 120)}`);
    }
    if (partials.length > 10) lines.push(`- _...and ${partials.length - 10} more_`);
    lines.push('');
  }

  // ─── Footer ─────────────────────────────────────────────────
  lines.push('---');
  lines.push(`*Generated by [\`@weave_protocol/adversary\`](https://www.npmjs.com/package/@weave_protocol/adversary) v${adversaryVersion}*`);

  return lines.join('\n');
}

function truncate(s: string, n: number): string {
  s = s.replace(/\s+/g, ' ').trim();
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
