/**
 * Markdown report renderer.
 *
 * Output is designed to be pasted into a blog post, vendor RFP response,
 * GitHub issue, or internal slide deck. Optimized for skimmability:
 * tier and score at the top, key findings inline, scorecard at the bottom.
 */

import type { Report } from '../types.js';

const TIER_BANNER: Record<string, string> = {
  A: '🟢 Tier A',
  B: '🟡 Tier B',
  C: '🟠 Tier C',
  D: '🔴 Tier D',
  F: '⚫ Tier F',
};

const SEVERITY_ICON: Record<string, string> = {
  severe: '🔴',
  moderate: '🟠',
  minor: '🟡',
  clean: '🟢',
};

const TROPHY_ICON: Record<string, string> = {
  pass: '✅',
  partial: '🟡',
  fail: '❌',
};

export function renderMarkdownReport(report: Report): string {
  const lines: string[] = [];
  const { target, suite, result, run, categoryGaps, trophyPerformance, wardDelta, interpretation } = report;

  // ─── Header ─────────────────────────────────────────────
  lines.push(`# 🎯 AgentSecBench Report`);
  lines.push('');
  lines.push(`**Target:** ${target.name}${target.vendor ? ` _(${target.vendor})_` : ''}${target.anonymized ? ' _(anonymized)_' : ''}`);
  lines.push(`**Type:** \`${target.type}\``);
  lines.push(`**Suite:** \`${suite.id}\` v${suite.version}`);
  lines.push(`**Date:** ${run.date}`);
  lines.push(`**Run by:** \`@weave_protocol/agentsecbench@${run.agentsecbenchVersion}\` (Adversary v${run.adversaryVersion})`);
  if (target.configuration && Object.keys(target.configuration).length > 0) {
    lines.push(`**Configuration:**`);
    for (const [k, v] of Object.entries(target.configuration)) {
      lines.push(`  - \`${k}\`: ${v}`);
    }
  }
  lines.push('');

  // ─── Headline result ────────────────────────────────────
  lines.push(`## ${TIER_BANNER[result.tier]} · Score: **${result.score}** / 100`);
  lines.push('');
  lines.push(
    `${result.blocked} blocked · ${result.partial} partial · ${result.breached} breached _(out of ${run.attacksRun} attacks in ${(run.durationMs / 1000).toFixed(1)}s)_`,
  );
  lines.push('');

  // ─── Interpretation prose ───────────────────────────────
  if (interpretation) {
    lines.push(`> ${interpretation}`);
    lines.push('');
  }

  // ─── Trophy performance ────────────────────────────────
  lines.push(`## 🏆 Documented in-the-wild attacks`);
  lines.push('');
  lines.push(`Performance against named, real-world agent attacks reproduced in the suite:`);
  lines.push('');
  lines.push('| Attack | Result |');
  lines.push('|---|---|');
  for (const trophy of trophyPerformance) {
    lines.push(`| **${trophy.name}** | ${TROPHY_ICON[trophy.result]} ${trophy.result} |`);
  }
  lines.push('');

  // ─── Category gaps ──────────────────────────────────────
  lines.push(`## 📊 Category-level analysis`);
  lines.push('');
  lines.push('| Category | Breach rate | Partial rate | Severity |');
  lines.push('|---|--:|--:|---|');
  for (const gap of categoryGaps) {
    lines.push(
      `| \`${gap.category}\` | ${(gap.breachRate * 100).toFixed(1)}% | ${(gap.partialRate * 100).toFixed(1)}% | ${SEVERITY_ICON[gap.severity]} ${gap.severity} |`,
    );
  }
  lines.push('');

  // ─── WARD delta ─────────────────────────────────────────
  if (wardDelta) {
    lines.push(`## 🛡️ WARD policy adherence`);
    lines.push('');
    if (wardDelta.withoutWard === 'unknown') {
      lines.push(`WARD policy loaded — score with WARD: **${wardDelta.withWard}**. (No-WARD baseline not measured.)`);
    } else {
      const sign = wardDelta.delta > 0 ? '+' : '';
      lines.push(`| Configuration | Score |`);
      lines.push(`|---|--:|`);
      lines.push(`| With WARD policy | **${wardDelta.withWard}** |`);
      lines.push(`| Without WARD policy | ${wardDelta.withoutWard} |`);
      lines.push(`| Net WARD contribution | **${sign}${wardDelta.delta}** |`);
    }
    lines.push('');
  }

  // ─── How to reproduce ──────────────────────────────────
  lines.push(`## 🔁 Reproducibility`);
  lines.push('');
  lines.push('```bash');
  lines.push(`npx @weave_protocol/agentsecbench run --suite=${suite.id} --target=<your-target>`);
  lines.push('```');
  lines.push('');
  lines.push(`Suite \`${suite.id}\` is **locked at v${suite.version}** — its 40 attack IDs and methodology cannot change. See [METHODOLOGY.md](https://github.com/Tyox-all/Weave_Protocol/blob/main/agentsecbench/METHODOLOGY.md).`);
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by [\`@weave_protocol/agentsecbench\`](https://www.npmjs.com/package/@weave_protocol/agentsecbench) v${run.agentsecbenchVersion}*`);

  return lines.join('\n');
}
